DefaultContentLanguage = "ja"
languageCode = "ja-JP"

baseURL = "https://pepese.github.io/"
title = "ぺーぺーSEのまとめ"
theme = "docport"
enableRobotsTXT = true
googleAnalytics = "UA-42388425-3"
pluralizeListTitles = false # Sectionのタイトル名複数形を防ぐ

[Author]
  name = "ぺーぺーSE"
  bio = "ぺーぺーSEがきまぐれでテックネタをまとめる。"
  avatar = "img/yaruwo.gif"

[Params]
  description = "備忘録用メモサイト"
  twitter_cards = true
  color_main = "#737373"
  color_second = "#b30000"
  disableSearch = true
  mathjax = true

[Params.widgets.social]
  twitter = "@PeePeeSE"
  github = "pepese"